////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace NosTale.Packets.Packets.CommandPackets
{
    [PacketHeader("$Unlock", PassNonParseablePacket = true, Authorities = new[] { AuthorityType.User })]
    public class UnlockPacket : PacketDefinition
    {
        #region Methods

        public static string ReturnHelp() => "$Unlock <Code>";

        #endregion

        #region Properties

        [PacketIndex(0)]
        public string Code { get; set; }

        #endregion
    }
}
